# Student Success and Wellbeing Index

- **Module:** Data Analysis and Visualization
- **Assessment:** CA1 - Composite Indicator
- **Student Name:** Liam Moore
- **Student Number:** D00254813

## Introduction

- The aim of my project is to create a composite indicator called the **Student Sucess and Wellbeing Index**. The purpose of this index is to combine different aspects of student life into a single score.

- The dataset I selected includes variables such as **Study_Hours_Per_Day**, **Extracurricular_Hours_Per_Day**, **Sleep_Hours_Per_Day**, **Social_Hours_Per_Day**, **Physical_Activity_Hours_Per_Day**, **GPA**, and **Stress_Level**. I choose these as they all play a role in a students overall performance and wellbeing.

- I will clean the data, normalise it, and group it into smaller sub indicies before combining them into a final score. I will also preform basic analysis to understand the relationship between the variables.

- The index will allow students to be compared and will help show how different lifestyle factors can affect a students academic success and overall wellbeing.

# Theoretical Framework

- A composite indicator is a single score created by combining multiple variables. It is useful whhen trying to measure something complex that cannot be represented by one value.

- For this project, the Student Success and Wellbeiing Indeex is made up of three main components:
    - **Academic Performance** (GPA and Study_Hours_Per_Day)
    - **Wellbeing** (Sleep_Hours_Per_Day and Stress_Level)
    - **Lifestyle** (Social_Hours_Per_Day, Physical_Activity_Hours_Per_Day, and Extracurricular_Hours_Per_Day)

- The reason that I chose the variables is because they are important factors that heavily influence how well a student performs. For example, good sleep and low stress can improve a students focus , while physical activity and social activities contribute to a students overall wellbeing.

- By combining these factors into a single index, it is possible to compare student and better understand what leads to success.

## Data Selection

- For the projeect, I selected a student lifestyle dataset froom kaggle containing around 2000 rows of data. Each row represents a student and includes information about their daily activities and academic performance. 

- The dataset includes variables such as **study hours**, **sleep hours**, **social activity**, **physical activity**, **extracurricular activity**, **GPA**, and **stress level**.

- I chose the dataset because It included a good mix of academic and lifestyle factors, which are both important  when measuring student success and wellbeing. Most of the variables are numerical, making them suitable for analysis, normalisation, and building a composite index.

- The size of the dataset also makes it useful for identifying patterns and carrying out further analysis such as clustering and visualisation.

# Handling Missing Data & Cleaning

In [1]:
import pandas as pd

df = pd.read_csv('student_lifestyle_dataset.csv')

df.head()

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,Moderate
1,2,5.3,3.5,8.0,4.2,3.0,2.75,Low
2,3,5.1,3.9,9.2,1.2,4.6,2.67,Low
3,4,6.5,2.1,7.2,1.7,6.5,2.88,Moderate
4,5,8.1,0.6,6.5,2.2,6.6,3.51,High

In [2]:
df.isnull().sum()

Student_ID                         0
Study_Hours_Per_Day                0
Extracurricular_Hours_Per_Day      0
Sleep_Hours_Per_Day                0
Social_Hours_Per_Day               0
Physical_Activity_Hours_Per_Day    0
GPA                                0
Stress_Level                       0
dtype: int64

- I checked the dataset for missing values using the **isnull()** function.

- The result shows that there is no missing values in any of the variables within the dataset, meaning it's complete. Because of this I did'nt have to remove any data.

- If there had of been missing values within the dataset I would of handled it by estimating them using the mean of the variable.

In [3]:
stress = {
    "Low": 1,
    "Moderate": 2,
    "High": 3
}

df['Stress_Level'] = df['Stress_Level'].map(stress)

df.head()

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,6.9,3.8,8.7,2.8,1.8,2.99,2
1,2,5.3,3.5,8.0,4.2,3.0,2.75,1
2,3,5.1,3.9,9.2,1.2,4.6,2.67,1
3,4,6.5,2.1,7.2,1.7,6.5,2.88,2
4,5,8.1,0.6,6.5,2.2,6.6,3.51,3

- I noticed in the dataset that the Stress_Level variable was originally categorical, the values were "Low", "Moderate", and "High".

- I converted the variable into numerical values (1, 2, 3) so that it can be used in calculations and included in the index.

## Normalisation

- The variables in the dataset are measure on different scales. For example, GPA is measured on a smaller scale compared to variables such as study hours or sleep hours.

- Because of this, I need to normalise the data so that all variables can be compared fairly. If normalisation was conducted, variables with larger values (e.g. Sleep Hours) could have a bigger influence on the final index.

- For my dataset, I used Min Max normalisation which I used in previous modules(AI, Data Science)to scale all of the variables between 0 and 1.

In [4]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols = [
    "Study_Hours_Per_Day",
    "Extracurricular_Hours_Per_Day",
    "Sleep_Hours_Per_Day",
    "Social_Hours_Per_Day",
    "Physical_Activity_Hours_Per_Day",
    "GPA",
    "Stress_Level"
]

df[cols] = scaler.fit_transform(df[cols])

df["Stress_Level"] = 1 - df["Stress_Level"]

df.head()

,Student_ID,Study_Hours_Per_Day,Extracurricular_Hours_Per_Day,Sleep_Hours_Per_Day,Social_Hours_Per_Day,Physical_Activity_Hours_Per_Day,GPA,Stress_Level
0,1,0.38,0.950,0.74,0.466667,0.138462,0.426136,0.5
1,2,0.06,0.875,0.60,0.700000,0.230769,0.289773,1.0
2,3,0.02,0.975,0.84,0.200000,0.353846,0.244318,1.0
3,4,0.30,0.525,0.44,0.283333,0.500000,0.363636,0.5
4,5,0.62,0.150,0.30,0.366667,0.507692,0.721591,0.0